### ISSUE TITLE
Optional Map

### ISSUE THREAD

**Issue by calebkleveter** [vapor/nio-kit#1]
Add `optionalMap` and `optionalFlatMap` methods to `EventLoopFuture`  where the callback is only fired if the optional value in the future is _not nil_:

```swift
let id: Future<Int?> = ...
id.optionalMap { id in
    type(of: id) // Int
}
```

**Comment by tanner0101** [comment]
+1 to this.

I think it could make sense to flip the words though, to better match #2.

```swift
let id: Future<Int?> = ...
id.mapOptional { id in
    type(of: id) // Int
}
id.thenOptional { id in
    type(of: id) // Int
}
```

**Comment by John-Connolly** [comment]
Maybe it would be useful to add more monad transformers? For instance. 

```swift
let ids: Future<[Int]> = ...
ids.mapArray { id in
    type(of: ids) // Int
}
ids.thenArray { id in
    type(of: id) // Int
}
```

Unfortunately I don't think there is a generic way of writing these without Higher Kinded types.

**Comment by John-Connolly** [comment]
Just realized there was already an issue for this, oops. Ignore my previous comment! I think adding these is a great idea.
