### ISSUE TITLE
NIOTestCase

### ISSUE THREAD

**Issue by tanner0101** [vapor/nio-kit#5]
Consider adding an `XCTestCase` subclass to make the following boilerplate easier:

```swift
class MyTest: XCTestCase {
    private var group: EventLoopGroup!
    private var eventLoop: EventLoop {
        return self.group.next()
    }

    func setUp() {
        self.group = MultiThreadedEventLoopGroup(numberOfThreads: ...)
    }

    func tearDown() {
        XCTAssertNoThrow(self.group.syncShutdownGracefully())
        self.group = nil
    }

   [...]
```

I think this could be possible with the `#if canImport(XCTest)`, but I'm not sure. We should look into it.

**Comment by MrLotU** [comment]
Why would you need the `#if canImport(XCTest)`? You could just declare this in the tests module right?

**Comment by calebkleveter** [comment]
The only reason I see this being useful, is if I have access the to `group` and `eventLoop` properties, but I don't think you can access private properties in a sub-class, right?

```swift
class MyTest: NIOTestCase {
    func testAllTheThings()throws {
        print(self.eventLoop)
    }
}

**Comment by MrLotU** [comment]
I have a setup like this now:
```swift
protocol NIOKitTestCaseProt: class {
    var group: EventLoopGroup! { get set }
}

extension NIOKitTestCaseProt {
    internal var eventLoop: EventLoop {
        return self.group.next()
    }
    
    internal func setupGroup() {
        self.group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
    }
    
    internal func teardownGroup() {
        XCTAssertNoThrow(try self.group.syncShutdownGracefully())
        self.group = nil
    }
}

class NIOKitTestCase: XCTestCase, NIOKitTestCaseProt {
    var group: EventLoopGroup!
    
    override func setUp() {
        super.setUp()
        setupGroup()
    }
    
    override func tearDown() {
        teardownGroup()
        super.tearDown()
    }
}
```

With the actual test looking like this
```swift
final class NIOKitTests: NIOKitTestCase {
    func testUniverseSanity() {
        print(self.eventLoop)
        XCTAssert(true)
    }

    static let allTests = [
        ("testUniverseSanity", testUniverseSanity)
    ]
}
```
Compiles and runs fine. Properties, however, can not be declared private, and I don't think there's a workable solution to that issue either. So I think internal is the best you can do without writing the same code over and over

**Comment by tanner0101** [comment]
@MrLotU have you tried putting that code in the `NIOKit` module and importing it into a test case yet? I think you will have problems importing `XCTest` from a non-test module.

**Comment by MrLotU** [comment]
I have not, but why would I want it in there? 🤔 Just having it in the test module is fine right?

**Comment by calebkleveter** [comment]
But then other packages can't use it as a dependency when they are testing NIO types.

**Comment by MrLotU** [comment]
Ah, yeah....

**Comment by MrLotU** [comment]
@tanner0101 @calebkleveter Just tested this, and it works just fine putting it in NIOKit 🎉 I'll open a PR
